name: Build & push latest Docker image
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get Project Version from pom.xml
      id: getProjectVersion
      uses: entimaniac/read-pom-version-action@1.0.0
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/itavsa/portal-back:${{ steps.getProjectVersion.outputs.version }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Push the Docker image
      run: docker push ghcr.io/itavsa/portal-back:${{ steps.getProjectVersion.outputs.version }}
