name: Build & push latest Docker image
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  getProjectVersion:
    runs-on: ubuntu-latest
    container: maven:3.9-amazoncorretto-20
    steps:
    - uses: actions/checkout@v3
    - name: Get project version from pom.xml
      id: getVersion
      run: echo version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) >> $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.getVersion.outputs.version }}
  buildPush:
    needs: getProjectVersion
    runs-on: ubuntu-latest
    env:
        VERSION: ${{ needs.getProjectVersion.outputs.version }}
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/itavsa/portal-back:$VERSION
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Push the Docker image
      run: docker push ghcr.io/itavsa/portal-back:$VERSION
